In [8]:
import cv2
import numpy as np
from google.colab import drive
import os
drive.mount('/content/gdrive')
from google.colab.patches import cv2_imshow

#criteria = (3, 30, 0.001)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
objp = np.zeros((48,3), np.float32)
objp[:,:2] = (np.mgrid[0:8,0:6].T.reshape(-1,2))

In [0]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

squaresize = 84
objp = np.zeros((48,3), np.float32)
objp[:,:2] = (np.mgrid[0:8,0:6].T.reshape(-1,2))*squaresize
imgpoints_l = []
imgpoints_r = []
objpoints = [] 
path_l = "/content/gdrive/My Drive/CV_Assignment-6/Lab6/cam1/"
path_r = "/content/gdrive/My Drive/CV_Assignment-6/Lab6/cam2/"
files = os.listdir(path_l);
for fname in files:
  img_l = cv2.imread(path_l + fname)
  gray_l = cv2.cvtColor(img_l,cv2.COLOR_BGR2GRAY)
  #cv2_imshow(img_l)
  img_r = cv2.imread(path_r + fname)
  gray_r = cv2.cvtColor(img_r,cv2.COLOR_BGR2GRAY)
  
  ret_l, corners_l = cv2.findChessboardCorners(gray_l, (8,6),None)
  ret_r, corners_r = cv2.findChessboardCorners(gray_r, (8,6),None)

  if ret_l == True and ret_r == True:
    #print(fname);
    objpoints.append(objp)

    corners2_l = cv2.cornerSubPix(gray_l,corners_l,(11,11),(-1,-1),criteria)
    imgpoints_l.append(corners2_l)

    corners2_r = cv2.cornerSubPix(gray_r,corners_r,(11,11),(-1,-1),criteria)
    imgpoints_r.append(corners2_r)

In [0]:
retl, mtxl, distl, rvecsl, tvecsl = cv2.calibrateCamera(objpoints, imgpoints_l, (1000, 666),None,None)
retr, mtxr, distr, rvecsr, tvecsr = cv2.calibrateCamera(objpoints, imgpoints_r, (1000, 666),None,None)

In [0]:
ret,mtx1,dist1,mtx2,dist2,R,T,E,F = cv2.stereoCalibrate(objpoints,imgpoints_l,imgpoints_r,mtxl,distl,mtxr,distr,(1000,666))#,mtxl,distl,mtxr,distr)

In [13]:
F

array([[ 1.68737375e-08, -1.11647671e-06,  1.48091226e-03],
       [ 1.09876194e-06,  1.15079778e-09, -2.10276655e-03],
       [-1.46993852e-03,  1.33623495e-03,  1.00000000e+00]])

In [14]:
mtxl

array([[4.28083436e+03, 0.00000000e+00, 2.63186700e+03],
       [0.00000000e+00, 4.27896047e+03, 1.73758746e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [16]:
mtxr

array([[3.36572360e+04, 0.00000000e+00, 6.62894923e+02],
       [0.00000000e+00, 3.38286299e+04, 2.24416208e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [17]:
mtx2

array([[3.36572360e+04, 0.00000000e+00, 6.62894923e+02],
       [0.00000000e+00, 3.38286299e+04, 2.24416208e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])